############################# Input ############################################
httpbeat:

  urls:
    # Each - URL endpoints to poll. Below are the URL endpoint specific configurations
    -
      url: http://httpbin.org/headers

      # HTTP method to use.
      # Possible options are:
      # * get
      # * delete
      # * head
      # * patch
      # * post
      # * put
      method: get

      #body:

      #basic_auth:
        #username:
        #password:

      # Default is every 1 minute.
      #cron:

      #proxy_url: http://proxy:3128
      #timeout: 60

      #tls:
        #certificate_authorities: ["/etc/pki/root/ca.pem"]
        #certificate: "/etc/pki/client/cert.pem"
        #certificate_key: "/etc/pki/client/cert.key"

        # Controls whether the client verifies server certificates and host name.
        # If insecure is set to true, all server host names and certificates will be accepted. 
        # /!\ man-in-the-middle attacks /!\ Use only for testing.
        #insecure: true

        #cipher_suites: []
        #curve_types: []
        #min_version: "1.0"
        #max_version: "1.2"

      #document_type: httpbeat
      #headers:
      # to add additional information
      #fields:

############################# Output ##########################################

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.
output:

  ### Elasticsearch as output
  elasticsearch.hosts: ["localhost:9200"]

  #elasticsearch.username: "admin"
  #elasticsearch.password: "s3cr3t"
  #elasticsearch.protocol: "https"  

  #elasticsearch.worker: 1
  #elasticsearch.index: "filebeat"
  #elasticsearch.path: "/elasticsearch"
  #elasticsearch.proxy_url: http://proxy:3128


  #elasticsearch.max_retries: 3
  #elasticsearch.bulk_max_size: 50
  #elasticsearch.timeout: 90
  #elasticsearch.flush_interval: 1

  #elasticsearch.tls:
    #certificate_authorities: ["/etc/pki/root/ca.pem"]
    #certificate: "/etc/pki/client/cert.pem"
    #certificate_key: "/etc/pki/client/cert.key"

    # Controls whether the client verifies server certificates and host name.
    # If insecure is set to true, all server host names and certificates will be accepted. 
    # /!\ man-in-the-middle attacks /!\ Use only for testing.
    #insecure: true
    #insecure: true

    #cipher_suites: []
    #curve_types: []

############################# Logging #########################################

# There are three options for the log ouput: syslog, file, stderr.
# Under Windos systems, the log files are per default sent to the file output,
# under all other system per default to syslog.
#logging:

  #to_syslog: true
  #to_files: false
  #files:
    #path: /var/log/mybeat
    #name: mybeat
    #rotateeverybytes: 10485760 # = 10MB
    #keepfiles: 7

# beat, publish, service.To enable all selectors use ["*"]
  #selectors: [ ]
  # critical, error, warning, info, debug
  #level: error